### ISSUE TITLE
Calculate the bounding box with a point and radius

### ISSUE THREAD

**Issue by nimashariatian** [yltsrc/geocalc#17]
hi guys,
first of all, thank you so much for this library!
its amazing ! 

i just wanted to make a suggestion, it would be great if we could
calculate the bounding box coordinates of a given point at its center along with a radius.

use case: 
assuming, having bunch of points saved in the database (longitudes an latitudes), 
this could help us find records that are within X miles / kms of a given point.

here is an example of ruby implementation:
https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/calculations.rb#L212

again,
thanks for all the hard work :)

**Comment by yltsrc** [comment]
PRs are welcome :)
in other way I can do it, but I can't say when...

**Comment by nimashariatian** [comment]
perfect, ill fork and work on it i guess.. i am actually kind of hoping to eventually do a pour of the entire https://github.com/alexreisner/geocoder/blob/master/lib/geocoder 
from ruby -> elixir

**Comment by jeffdeville** [comment]
@nimashariatian FYI, PR created
