### ISSUE TITLE
OTP app vs plain module

### ISSUE THREAD

**Issue by grin** [yltsrc/geocalc#20]
Hi,

Is there any particular reason this library is implemented as an OTP app with a supervision tree and not a plain module just exposing calc functions?

Thanks!

**Comment by yltsrc** [comment]
Actually not,
but one of the functions can crash (and I have guards around that place) so I planned to remove them and make it 100% the same as in the original javascript version and let it crash

So it is the actual question and I can't find an answer when to use OTP and when I should not

BTW: version 0.4.0 was implemented without OTP

**Comment by grin** [comment]
According to this comment: https://www.amberbit.com/blog/2016/5/10/creating-elixir-libraries-as-otp-applications/#comment-2677186959 all libraries should be an OTP apps, but not all libraries should have the supervision tree.

Libraries that don't start any processes thus don't need supervision trees are called library application (as per https://elixirforum.com/t/design-otp-app-vs-modules-of-pure-functions/869/4).

**Comment by yltsrc** [comment]
https://github.com/yltsrc/geocalc/pull/32
